/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocColorPicker: typeof import('./.vitepress/components/DocColorPicker.vue')['default']
    DocDemoBox: typeof import('./.vitepress/components/DocDemoBox.vue')['default']
    DocForm: typeof import('./.vitepress/components/DocForm.vue')['default']
    DocFormItem: typeof import('./.vitepress/components/DocFormItem.vue')['default']
    DocInputNumber: typeof import('./.vitepress/components/DocInputNumber.vue')['default']
    DocSwitch: typeof import('./.vitepress/components/DocSwitch.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSwitch: typeof import('naive-ui')['NSwitch']
  }
}
